# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"

#[main.params]
#icon = "shnks.png"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ShaanksM"

[social.params]
icon = "brand-github"

[[social]]
identifier = "hack the box"
name = "Hack The Box"
url = "https://app.hackthebox.com/profile/382091"

[social.params]
icon = "hackthebox"

[[social]]
identifier = "Root Me"
name = "Root Me"
url = "https://www.root-me.org/0xShaanks?lang=fr#8403af773d506c0b99723cabb030ab8f"

[social.params]
icon = "rootme"